services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.13
    volumes:
      - /mnt/docker-storage/homepage/config:/app/config
      - /mnt/docker-storage/homepage/icons:/app/public/icons
      - /mnt/docker-storage/homepage/images:/app/public/images
      - /mnt/docker-storage:/nasstorage:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ="America/New_York"
    extra_hosts:
      raspi1: 10.0.0.82
      raspi2: 10.0.0.130
      raspi3: 10.0.0.223
      raspizero: 10.0.0.190
      penguinnas: 10.0.0.114
      ender3v2: 10.0.0.156
    networks:
      - swarm_network
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
networks:
  swarm_network:
    external: true