version: '3.2'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.13
    volumes:
      - /mnt/docker-storage/homepage/config:/app/config
      - /mnt/docker-storage/homepage/icons:/app/public/icons
      - /mnt/docker-storage/homepage/images:/app/public/images
      - /data/glusterfs/swarmvol/brick1:/mnt/docker-storage
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ="America/New_York"
    networks:
      - swarm_network
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  swarm_network:
    driver: overlay
    attachable: true
    external: true