services:
  npm:
    image: jc21/nginx-proxy-manager:2.12.1
    volumes:
      - /mnt/docker-storage/npm/data:/data
      - /mnt/docker-storage/npm/letsencrypt:/etc/letsencrypt
    environment:
      - "TZ=America/New_York"
    networks:
      - swarm_network
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - homepage.group=Network
        - homepage.name=NGINX Proxy Manager
        - homepage.href=http://nginx.lan/
        - homepage.description=Reverse Proxy
        - homepage.icon=/icons/npmicon.png
        - homepage.widget.type=npm
        - homepage.widget.url=http://npm_npm:81
        - homepage.widget.username=jorgeart0208@gmail.com
        - homepage.widget.password=OreoMolly@1
networks:
  swarm_network:
    external: true