services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - swarm_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/docker-storage/portainer/data:/data
      - /usr/share/zoneinfo/America/New_York:/etc/localtime
    environment:
      - "TZ=America/New_York"
    networks:
      - swarm_network
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - homepage.group=Docker
        - homepage.name=Portainer
        - homepage.href=http://portainer.lan/
        - homepage.description=Docker Management
        - homepage.icon=/icons/portainericon.png
        - homepage.widget.type=portainer
        - homepage.widget.url=http://portainer_portainer:9000
        - homepage.widget.env=1
        - homepage.widget.key=ptr_dvUOVnaHgQyCJgxz18LIqQ0Z96dyocVxMVmJ80/4DEM=
networks:
  swarm_network:
    external: true
