services:
  trilium:
    image: zadam/trilium:0.63-latest
    volumes:
      - /mnt/docker-storage/trilium/data:/home/node/trilium-data
    networks:
      - swarm_network
    ports:
      - "8888:8080"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - homepage.group=Notes
        - homepage.name=Trilium
        - homepage.href=http://trilium.lan/
        - homepage.description=Web based notes
        - homepage.icon=/icons/triliumicon.png
networks:
  swarm_network:
    external: true
