version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server:1.32.5
    volumes:
      - /mnt/docker-storage/vaultwarden/data:/data
    environment:
      WEBSOCKET_ENABLED: "true"  # Enable WebSocket notifications.
      SHOW_PASSWORD_HINT: "false"
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "false"
    networks:
      - swarm_network
    ports:
      - "9080:80"
      - "3012:3012"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - homepage.group=Password Manager
        - homepage.name=Vaultwarden
        - homepage.href=https://vw.penguinhs.com/
        - homepage.description=Password Manager
        - homepage.icon=/icons/vaultwardenicon.png
networks:
  swarm_network:
    external: true