version: '3.2'

services:
  wgeasy:
    image: ghcr.io/wg-easy/wg-easy:latest
    volumes:
      - /mnt/docker-storage/wgeasy:/app/config
    environment:
      - TZ="America/New_York"
      - LANG=de
      - WG_HOST=vpn.penguinhs.com
      - PASSWORD_HASH=$$2a$$12$$lNnQZDSLD5HC5fUmf6Fda.xMzj1kQ3yBztz/QJrdyjZ4YXqE736GK
      - WG_DEFAULT_DNS=10.0.0.190
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:
      - swarm_network
    ports:
      - "51820:51820/udp"
      - "51821:51821"
    deploy:
      mode: replicated
      replicas: 1
networks:
  swarm_network:
    driver: overlay
    attachable: true
    external: true